### ISSUE TITLE
不能解压分包

### ISSUE THREAD

**Issue by wqf525** [system-cpu/wxappUnpacker#1]
微信用的夜神模拟器打开，清空微信文件夹下所有的wxapkg

打开小程序，然后得到分包主包，命名为master.wxapkg,slave1.wxapkg,slave2.wxapkg

主包执行
.\bingo.sh .\g\master.wxapkg

分包执行
 .\bingo.sh -s=g\master .\g\slave1.wxapkg

```
Unpack done.
now dir: C:\Users\l\Desktop\wxappUnpacker-master\g\_705887512_4
param of mainDir: g/slave1
subpack C:\Users\l\Desktop\wxappUnpacker-master\g\_705887512_4 C:\Users\l\Desktop\wxappUnpacker-master\g\_705887512_4
subpack C:\Users\l\Desktop\wxappUnpacker-master\g\_705887512_4\GameSceneAll C:\Users\l\Desktop\wxappUnpacker-master\g\_705887512_4
subpack C:\Users\l\Desktop\wxappUnpacker-master\g\_705887512_4\GameSceneAll\Conventional C:\Users\l\Desktop\wxappUnpacker-master\g\_705887512_4
subpack C:\Users\l\Desktop\wxappUnpacker-master\g\_705887512_4\GameSceneAll\Conventional\Assets C:\Users\l\Desktop\wxappUnpacker-master\g\_705887512_4
subpack C:\Users\l\Desktop\wxappUnpacker-master\g\_705887512_4\GameSceneAll\Conventional\Assets\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA C:\Users\l\Desktop\wxappUnpacker-master\g\_705887512_4
subpack C:\Users\l\Desktop\wxappUnpacker-master\g\_705887512_4\GameSceneAll\Conventional\Assets\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\New Material 3.lmat C:\Users\l\Desktop\wxappUnpacker-master\g\_705887512_4
internal/fs/utils.js:259
    throw err;
    ^

Error: ENOTDIR: not a directory, scandir 'C:\Users\l\Desktop\wxappUnpacker-master\g\_705887512_4\GameSceneAll\Conventional\Assets\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\New Material 3.lmat'
    at Object.readdirSync (fs.js:974:3)
    at findDir (C:\Users\l\Desktop\wxappUnpacker-master\wuWxapkg.js:155:36)
    at findDir (C:\Users\l\Desktop\wxappUnpacker-master\wuWxapkg.js:166:29)
    at findDir (C:\Users\l\Desktop\wxappUnpacker-master\wuWxapkg.js:166:29)
    at findDir (C:\Users\l\Desktop\wxappUnpacker-master\wuWxapkg.js:166:29)
    at findDir (C:\Users\l\Desktop\wxappUnpacker-master\wuWxapkg.js:166:29)
    at findDir (C:\Users\l\Desktop\wxappUnpacker-master\wuWxapkg.js:166:29)
    at Array.packDone (C:\Users\l\Desktop\wxappUnpacker-master\wuWxapkg.js:172:17)
    at CntEvent.decount (C:\Users\l\Desktop\wxappUnpacker-master\wuLib.js:20:54)
    at C:\Users\l\Desktop\wxappUnpacker-master\wuLib.js:88:17 {
  errno: -4052,
  syscall: 'scandir',
  code: 'ENOTDIR',
  path: 'C:\\Users\\l\\Desktop\\wxappUnpacker-master\\g\\_705887512_4\\GameSceneAll\\Conventional\\Assets\\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\\New Material 3.lmat'
}


```

所以想问下大佬，分包解压的正确姿势！
感谢

**Comment by wqf525** [comment]
由于分包中，没有app-service.js，我将
···
 if (!doSubPkg) {
             throw new Error("检测到此包是分包后的子包, 请通过 -s 参数指定存放路径后重试, 如 node wuWxapkg.js -s=/xxx/xxx ./testpkg/test-pkg-sub.wxapkg");
         }
···

上面代码注释了，并且添加

···
 if (fs.statSync(dir).isFile()) {
                        return ;
                    }
···
在findDir方法，readdirSync之前，不知道这样有什么问题呢？还有个问题，我=s指定了master的文件夹，但是并没有将文件导入。

想知道这个是什么原因呢？谢谢

**Comment by zzzmj** [comment]
> 由于分包中，没有app-service.js，我将
> ···
> 如果（！doSubPkg）{
> throw new Error（“检测到此包是分包后的子包，请通过-s参数指定放置路径后重试，例如node wuWxapkg.js -s = / xxx / xxx ./testpkg/test-pkg-sub.wxapkg“）；
> }
> ···
> 
> 上面的代码注释了，并添加
> 
> ···
> 如果（fs.statSync（dir）.isFile（））{
> 返回；
> }
> ···
> 在findDir方法，readdirSync之前，不知道这样有什么问题呢？还有个问题，我= s指定了master的文件夹，但是并没有将文件导入。
> 
> 想知道这个是什么原因呢？谢谢

我也遇到了相同的问题，请问你解决了吗？@wqf525
