### ISSUE TITLE
大佬 麻烦帮忙看看这个是啥问题呀

### ISSUE THREAD

**Issue by WangSuwen** [system-cpu/wxappUnpacker#11]
eferenceError: ReadableStream is not defined
    at Object.<anonymous> (/Users/w/learning/wxappUnpacker/node_modules/undici/lib/web/fetch/response.js:527:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/Users/w/learning/wxappUnpacker/node_modules/undici/lib/web/fetch/index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)

**Comment by CagyFrancis** [comment]
我也遇到了类似的问题：
`node /home/njupt/projects/Mini-APP/wxappUnpacker/wuWxapkg.js 
/home/njupt/projects/Mini-APP/wxappUnpacker/node_modules/undici/lib/web/webidl/index.js:512
webidl.is.File = webidl.util.MakeTypeAssertion(File)
                                               ^

ReferenceError: File is not defined
    at Object.<anonymous> (/home/njupt/projects/Mini-APP/wxappUnpacker/node_modules/undici/lib/web/webidl/index.js:512:48)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/home/njupt/projects/Mini-APP/wxappUnpacker/node_modules/undici/lib/web/fetch/util.js:12:20)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)

Node.js v18.19.1`

**Comment by CagyFrancis** [comment]
我猜测是Node.js运行时的问题，比方说File在非浏览器环境里没有原生支持，所以报错了。
但我发现本项目好像没用到File类，所以我直接把/node_modules/undici/lib/web/webidl/index.js:512这一行注释掉了。
项目就正常运行了。

**Comment by TaHongLingBo** [comment]
我把node拉到22就正常了
