### ISSUE TITLE
请问这个怎么解决？

### ISSUE THREAD

**Issue by xiaohange** [system-cpu/wxappUnpacker#6]
```shell
Unpack done.
Split app-service.js and make up configs & wxss & wxml & wxs...
deal config ok
deal js ok
deal html ok
deal css ok
splitJs: /home/harry/wxappUnpacker-master/app/wx7ff71e40388d161c/app-service.js
/home/harry/wxappUnpacker-master/node_modules/vm2/lib/transformer.js:174
                throw makeNiceSyntaxError('Use of internal vm2 state variable', code, filename, internStateValiable.start, {
                ^

vm.js:4840
"use strict";function n(n,t,e,o,r,i,u){try{var c=n[i](u),_=c.value}catch(n){return void e(n=VM2_INTERNAL_STATE_DO_NOT_USE_OR_PROGRAM_WILL_FAIL.handleException(n))}c.done?t(_):Promise.resolve(_).then(o,r)}module.exports=function(t){return function(){var e=this,o=arguments;return new Promise((function(r,i){var u=t.apply(e,o);function c(t){n(u,r,i,c,_,"next",t)}function _(t){n(u,r,i,c,_,"throw",t)}c(void 0)}))}}; 
                                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Use of internal vm2 state variable
    at makeNiceSyntaxError (/home/harry/wxappUnpacker-master/node_modules/vm2/lib/transformer.js:41:16)
    at transformer (/home/harry/wxappUnpacker-master/node_modules/vm2/lib/transformer.js:174:9)
    at VM.run (/home/harry/wxappUnpacker-master/node_modules/vm2/lib/vm.js:491:16)
    at /home/harry/wxappUnpacker-master/wuJs.js:48:12
    at /home/harry/wxappUnpacker-master/wuLib.js:103:14
    at agent (/home/harry/wxappUnpacker-master/wuLib.js:66:23)
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

**Comment by x531tanxl** [comment]
所有 VM2_INTERNAL_STATE_DO_NOT_USE_OR_PROGRAM_WILL_FAIL 的这行都注释
